### ISSUE TITLE
Unable to access images

### ISSUE THREAD

**Issue by pickledolives** [getyourguide/thack-documentation#1]
Image URLs returned by the API do not work. How can I use them?

http://img-getyourguide-com-test3.gygtest.com/img/tour_img-315390-6.jpg

**Comment by xmajox** [comment]
Thanks for reporting this @pickledolives. We will try to sort it out as soon as possible.

**Comment by pickledolives** [comment]
I quick-fixed it with: 

`tour['pictures'].first['url'].sub('img-getyourguide-com-test3.gygtest', 'cdn2.getyourguide')` (Ruby)

That's probably not what you guys want.

**Comment by xmajox** [comment]
That is one way to do it :) We now fixed all links to point at the CDN correctly.

Thanks for reporting it, and good hacking!
